# Generated by Django 5.2.8 on 2026-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
