# Generated by Django 5.2.8 on 2026-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('page_visited', models.CharField(max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='home_visito_visited_cade49_idx'), models.Index(fields=['ip_address', 'visited_at'], name='home_visito_ip_addr_456d61_idx')],
            },
        ),
    ]
